2021-09-12 15:31:00,439 ERROR: Exception on /language/es [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Code\Personal\microblog\app\main\routes.py", line 148, in inject_language
    User.set_languge(language = language)
TypeError: set_languge() missing 1 required positional argument: 'self'
2021-09-12 15:31:50,009 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
2021-09-12 15:31:51,285 ERROR: Exception on /index [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "C:\Code\Personal\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
TypeError: get_locale() missing 1 required positional argument: 'language'
2021-09-12 15:32:33,153 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
2021-09-12 15:32:43,322 ERROR: Exception on /language/es [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Code\Personal\microblog\app\main\routes.py", line 148, in inject_language
    User.set_languge(language = language)
TypeError: set_languge() missing 1 required positional argument: 'self'
2021-09-12 15:33:08,365 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
2021-09-12 15:33:09,920 ERROR: Exception on /language/es [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Code\Personal\microblog\app\main\routes.py", line 148, in inject_language
    get_locale(language)
TypeError: get_locale() takes 0 positional arguments but 1 was given
2021-09-12 15:33:42,401 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
2021-09-12 15:33:46,320 ERROR: Exception on /language/es [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "C:\Code\Personal\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
TypeError: get_locale() missing 1 required positional argument: 'language'
2021-09-12 15:33:52,027 ERROR: Exception on /index [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "C:\Code\Personal\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
TypeError: get_locale() missing 1 required positional argument: 'language'
2021-09-12 15:34:07,810 ERROR: Exception on /language/es [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "C:\Code\Personal\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
TypeError: get_locale() missing 1 required positional argument: 'language'
2021-09-12 15:35:58,987 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
2021-09-12 15:37:24,319 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
2021-09-12 15:37:25,688 ERROR: Exception on /index [GET] [in c:\code\personal\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1511, in full_dispatch_request
    rv = self.preprocess_request()
  File "c:\code\personal\microblog\venv\lib\site-packages\flask\app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(func)()
  File "C:\Code\Personal\microblog\app\main\routes.py", line 19, in before_request
    g.locale = str(get_locale())
  File "c:\code\personal\microblog\venv\lib\site-packages\flask_babel\__init__.py", line 226, in get_locale
    rv = babel.locale_selector_func()
TypeError: inject_language() missing 1 required positional argument: 'language'
2021-09-12 15:38:30,895 INFO: Microblog startup [in C:\Code\Personal\microblog\app\__init__.py:73]
